
indexing-settings:
  sites:
    - url: https://nopaper.ru
      name: Nopaper.ru
    - url: https://nikoartgallery.com
      name: NikoartGallery.ru
    - url: https://playback.ru
      name: PlayBack
server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    #url: jdbc:postgresql://postgres:5432/search_engine
    url: jdbc:postgresql://localhost:5434/search_engine
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

connect-settings:
  userArgentValue: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

